package enamel;
/**
 *
 * @author kyleh
 */
public class AudioRecord extends javax.swing.JPanel {

    /**
     * Creates new form AudioRecord
     */
    public AudioRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bg = new javax.swing.JPanel();
        infoP = new javax.swing.JPanel();
        infoT = new javax.swing.JTextField();
        buttonP = new javax.swing.JPanel();
        recordB = new javax.swing.JButton();
        stopB = new javax.swing.JButton();
        playB = new javax.swing.JButton();
        exitB = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(1, 22, 56));

        infoP.setBackground(new java.awt.Color(54, 65, 85));

        infoT.setEditable(false);
        infoT.setBackground(new java.awt.Color(205, 205, 205));
        infoT.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        infoT.setForeground(new java.awt.Color(70, 70, 85));

        javax.swing.GroupLayout infoPLayout = new javax.swing.GroupLayout(infoP);
        infoP.setLayout(infoPLayout);
        infoPLayout.setHorizontalGroup(
            infoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(infoT, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        infoPLayout.setVerticalGroup(
            infoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(infoT, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        buttonP.setBackground(new java.awt.Color(54, 65, 85));

        recordB.setBackground(new java.awt.Color(205, 205, 205));
        recordB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        recordB.setForeground(new java.awt.Color(70, 70, 85));
        recordB.setText("Record");
        recordB.setActionCommand("Record");

        stopB.setBackground(new java.awt.Color(205, 205, 205));
        stopB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        stopB.setForeground(new java.awt.Color(70, 70, 85));
        stopB.setText("Stop");
        stopB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBActionPerformed(evt);
            }
        });

        playB.setBackground(new java.awt.Color(205, 205, 205));
        playB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        playB.setForeground(new java.awt.Color(70, 70, 85));
        playB.setText("Play");
        playB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBActionPerformed(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(205, 205, 205));
        exitB.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        exitB.setForeground(new java.awt.Color(70, 70, 85));
        exitB.setText("Add and Exit");
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPLayout = new javax.swing.GroupLayout(buttonP);
        buttonP.setLayout(buttonPLayout);
        buttonPLayout.setHorizontalGroup(
            buttonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPLayout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(stopB, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(808, Short.MAX_VALUE))
            .addGroup(buttonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonPLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(recordB, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(546, 546, 546)
                    .addComponent(playB, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(154, 154, 154)
                    .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        buttonPLayout.setVerticalGroup(
            buttonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(stopB, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(buttonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonPLayout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(buttonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(playB, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(recordB, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        recordB.getAccessibleContext().setAccessibleDescription("Record new audio");
        stopB.getAccessibleContext().setAccessibleDescription("Stop recording");
        playB.getAccessibleContext().setAccessibleDescription("Play the sound you recorded");
        exitB.getAccessibleContext().setAccessibleDescription("Add, save and exit the program while also adding the sudio to your file");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(buttonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(infoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(infoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(buttonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                        

    private void stopBActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void playBActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     


    // Variables declaration - do not modify                     
    private javax.swing.JPanel bg;
    private javax.swing.JPanel buttonP;
    private javax.swing.JButton exitB;
    private javax.swing.JPanel infoP;
    private javax.swing.JTextField infoT;
    private javax.swing.JButton playB;
    private javax.swing.JButton recordB;
    private javax.swing.JButton stopB;
    // End of variables declaration                   
}
