package enamel;

/**
* TEMPORY CLASS. THIS CLASS WILL HAVE UPDATED GUI FOR SCENARIO CREATOR. USING NETBEANS TO DESIGN
* @author kyleh
*/
public class NewJFrame extends javax.swing.JFrame {

   /**
    * Creates new form NewJFrame
    */
   public NewJFrame() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel2 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jTextArea1 = new javax.swing.JTextArea();
       inputMethodSlider = new javax.swing.JSlider();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       txtFldForBinary = new javax.swing.JTextField();
       rad1 = new javax.swing.JRadioButton();
       rad2 = new javax.swing.JRadioButton();
       rad3 = new javax.swing.JRadioButton();
       rad4 = new javax.swing.JRadioButton();
       rad5 = new javax.swing.JRadioButton();
       rad6 = new javax.swing.JRadioButton();
       rad7 = new javax.swing.JRadioButton();
       rad8 = new javax.swing.JRadioButton();
       radButNext = new javax.swing.JButton();
       radButBack = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Scenario Creator");
       setPreferredSize(new java.awt.Dimension(900, 800));
       setResizable(false);

       jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
       jPanel2.setToolTipText("Create your questions in this zone");
       jPanel2.setName(""); // NOI18N

       jLabel1.setText("Question Builder");

       jTextArea1.setColumns(20);
       jTextArea1.setRows(5);
       jTextArea1.setToolTipText("Enter your question here");
       jScrollPane1.setViewportView(jTextArea1);
       jTextArea1.getAccessibleContext().setAccessibleName("Question");

       inputMethodSlider.setMaximum(1);
       inputMethodSlider.setMinimum(-1);
       inputMethodSlider.setMinorTickSpacing(1);
       inputMethodSlider.setPaintLabels(true);
       inputMethodSlider.setPaintTicks(true);
       inputMethodSlider.setToolTipText("Slide to direction of what you would like to input with");
       inputMethodSlider.setValue(0);
       inputMethodSlider.addChangeListener(new javax.swing.event.ChangeListener() {
           public void stateChanged(javax.swing.event.ChangeEvent evt) {
               inputMethodSliderStateChanged(evt);
           }
       });
       inputMethodSlider.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               inputMethodSliderMouseClicked(evt);
           }
       });

       jLabel2.setText("Enter String");

       jLabel3.setText("Manually Enter");

       txtFldForBinary.setToolTipText("Enter word here");
       txtFldForBinary.setEnabled(false);

       rad1.setEnabled(false);

       rad2.setEnabled(false);
       rad2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               rad2ActionPerformed(evt);
           }
       });

       rad3.setEnabled(false);

       rad4.setEnabled(false);

       rad5.setEnabled(false);

       rad6.setEnabled(false);

       rad7.setEnabled(false);

       rad8.setEnabled(false);

       radButNext.setText(">");
       radButNext.setEnabled(false);

       radButBack.setText("<");
       radButBack.setEnabled(false);

       javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
       jPanel2.setLayout(jPanel2Layout);
       jPanel2Layout.setHorizontalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addComponent(jScrollPane1)
                       .addContainerGap())
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                       .addComponent(txtFldForBinary)
                       .addGap(260, 260, 260))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                       .addGap(0, 44, Short.MAX_VALUE)
                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                               .addComponent(jLabel1)
                               .addGap(136, 136, 136))
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                       .addComponent(jLabel2)
                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                       .addComponent(inputMethodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                       .addComponent(jLabel3))
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addGroup(jPanel2Layout.createSequentialGroup()
                                               .addGap(0, 0, Short.MAX_VALUE)
                                               .addComponent(radButBack))
                                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                   .addComponent(rad1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                   .addComponent(rad3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                   .addComponent(rad5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                   .addComponent(rad7, javax.swing.GroupLayout.Alignment.TRAILING))))
                                       .addGap(35, 35, 35)
                                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addComponent(rad4)
                                           .addComponent(rad2)
                                           .addComponent(rad6)
                                           .addComponent(rad8)
                                           .addComponent(radButNext))))
                               .addGap(33, 33, 33))))))
       );
       jPanel2Layout.setVerticalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addGap(27, 27, 27)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(rad6)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addComponent(jLabel1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel2Layout.createSequentialGroup()
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(inputMethodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                       .addGap(11, 11, 11)
                                       .addComponent(jLabel2))))
                           .addGroup(jPanel2Layout.createSequentialGroup()
                               .addGap(24, 24, 24)
                               .addComponent(jLabel3)))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                               .addComponent(txtFldForBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addComponent(rad1))
                           .addComponent(rad2))
                       .addGap(13, 13, 13)
                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(rad4)
                           .addComponent(rad3))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(rad5)))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(rad7)
                   .addComponent(rad8))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(radButNext)
                   .addComponent(radButBack))
               .addContainerGap(146, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(660, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 4, Short.MAX_VALUE))
       );

       jPanel2.getAccessibleContext().setAccessibleName("Question Builder");
       jPanel2.getAccessibleContext().setAccessibleDescription("This is the zone where you can create questions");

       setSize(new java.awt.Dimension(1126, 671));
       setLocationRelativeTo(null);
   }// </editor-fold>                        

   private void inputMethodSliderMouseClicked(java.awt.event.MouseEvent evt) {                                               
       
       // TODO add your handling code here:
       //test what value slider is and enable/disable the other option for input
       if(inputMethodSlider.isMaximumSizeSet() == true) {
           enableManual(true);
       }
   }                                              
/*
   Try to figure out how to update slider and change states 
   */
   private void enableManual(boolean set) {
       rad1.setEnabled(set);
       rad2.setEnabled(set);
       rad3.setEnabled(set);
       rad4.setEnabled(set);
       rad5.setEnabled(set);
       rad6.setEnabled(set);
       rad7.setEnabled(set);
       rad8.setEnabled(set);
       radButNext.setEnabled(set);
       radButBack.setEnabled(set);
}
   private void rad2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
       // TODO add your handling code here:
   }                                    

   private void inputMethodSliderStateChanged(javax.swing.event.ChangeEvent evt) {                                               
       // TODO add your handling code here:
       if(inputMethodSlider.getValue() == 1) {
           enableManual(true);
       } else if (inputMethodSlider.getValue() == -1) {
           txtFldForBinary.setEnabled(true);
       } else {
           enableManual(false);
           txtFldForBinary.setEnabled(false);
           
       }
   }                                                   

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("SystemLookAndFeel".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new NewJFrame().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JSlider inputMethodSlider;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JRadioButton rad1;
   private javax.swing.JRadioButton rad2;
   private javax.swing.JRadioButton rad3;
   private javax.swing.JRadioButton rad4;
   private javax.swing.JRadioButton rad5;
   private javax.swing.JRadioButton rad6;
   private javax.swing.JRadioButton rad7;
   private javax.swing.JRadioButton rad8;
   private javax.swing.JButton radButBack;
   private javax.swing.JButton radButNext;
   private javax.swing.JTextField txtFldForBinary;
   // End of variables declaration                   
}

