package enamel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JOptionPane;

/**
*
* @author kyleh
*/
public class starter extends javax.swing.JFrame  implements ActionListener {

   /**
    * Creates new form starter
    */
   public starter() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       bg = new javax.swing.JPanel();
       holder = new javax.swing.JPanel();
       nameT = new javax.swing.JTextField();
       cellT = new javax.swing.JTextField();
       butT = new javax.swing.JTextField();
       saveB = new javax.swing.JButton();
       exitB = new javax.swing.JButton();
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       bg.setBackground(new java.awt.Color(1, 22, 56));
       bg.setForeground(new java.awt.Color(1, 22, 56));

       holder.setBackground(new java.awt.Color(54, 65, 85));

       
       saveB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
       saveB.setText("Save and Continue");

       exitB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
       exitB.setText("Exit");

       jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
       jLabel1.setForeground(new java.awt.Color(223, 248, 235));
       jLabel1.setText("Enter the name of the file");

       jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
       jLabel2.setForeground(new java.awt.Color(223, 248, 235));
       jLabel2.setText("Enter the number of cells");

       jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
       jLabel3.setForeground(new java.awt.Color(223, 248, 235));
       jLabel3.setText("Enter the number of buttons");

       javax.swing.GroupLayout holderLayout = new javax.swing.GroupLayout(holder);
       holder.setLayout(holderLayout);
       holderLayout.setHorizontalGroup(
           holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(holderLayout.createSequentialGroup()
               .addGap(57, 57, 57)
               .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(holderLayout.createSequentialGroup()
                       .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel1)
                           .addComponent(jLabel2))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                           .addComponent(cellT, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                           .addComponent(nameT)))
                   .addGroup(holderLayout.createSequentialGroup()
                       .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel3)
                           .addGroup(holderLayout.createSequentialGroup()
                               .addGap(20, 20, 20)
                               .addComponent(saveB)))
                       .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(holderLayout.createSequentialGroup()
                               .addGap(34, 34, 34)
                               .addComponent(exitB)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, holderLayout.createSequentialGroup()
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                               .addComponent(butT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
               .addGap(65, 65, 65))
       );
       holderLayout.setVerticalGroup(
           holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(holderLayout.createSequentialGroup()
               .addGap(33, 33, 33)
               .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(nameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1))
               .addGap(63, 63, 63)
               .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(cellT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel2))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
               .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(butT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel3))
               .addGap(34, 34, 34)
               .addGroup(holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(saveB)
                   .addComponent(exitB))
               .addGap(35, 35, 35))
       );

       javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
       bg.setLayout(bgLayout);
       bgLayout.setHorizontalGroup(
           bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(bgLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap())
       );
       bgLayout.setVerticalGroup(
           bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(bgLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       saveB.addActionListener(this);
       exitB.addActionListener(this);
       pack();
   }// </editor-fold>    
   
   public static boolean cellAndButtonInt(String cell , String button) {
	    try { 
	        Integer.parseInt(cell); 
	        Integer.parseInt(button);
	    } catch(NumberFormatException e) { 
	        return false; 
	    } catch(NullPointerException e) {
	        return false;
	    }
	    if ((Integer.parseInt(cell) > 0)&&(Integer.parseInt(button) > 0) ) {
	    	return true;
	    } else {
	    	return false;
	    }
	
	}

   @Override
   public void actionPerformed(ActionEvent e) {
   	// TODO Auto-generated method stub
   		if(e.getActionCommand() == "Save and Continue") {
   			String fileName = nameT.getText().toString();
			String numOfCells = cellT.getText().toString();
			String numOfButtons = butT.getText().toString();
			File newFile = new File(System.getProperty("user.dir")+"/SavedScenarios/"+fileName+".txt");
			this.file = newFile;
			String newFilePath = newFile.getAbsolutePath();
			
			try {
				this.writer = new BufferedWriter(new FileWriter(newFile));
				if(cellAndButtonInt(numOfCells,numOfButtons)) {
					//writer.write("Cell " + numOfCells+"\n");
					//writer.write("Button " + numOfButtons+"\n");
					//writer.flush();
					this.dispose();
					
					this.cells = numOfCells;
					this.butt = numOfButtons;
					scenarioBuild sb = new scenarioBuild(this,numOfCells,numOfButtons);
					sb.setVisible(true);
					
					
					this.cells = numOfCells;
					this.butt = numOfButtons;
					
				}
					
					
				
					
				 else {
					JOptionPane.showMessageDialog(null, "Please enter a vaild number greater then 0", "WARNING", JOptionPane.WARNING_MESSAGE);
				}
			}catch(Exception e1) { 
		        
			}
				
			
			//
			
			
			
		 /*
		  * This closes the intital information panel
		  */
			
		} else if (e.getActionCommand() == "Exit") {
			int closeFrame = 0;
			String[] buttons = { "Yes", "No"};    
			int returnValue = JOptionPane.showOptionDialog(null, "Your file will not save. Do you wish to continue?","Exit" ,
			        JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[1]);
			
			if (returnValue == 0) {
				closeFrame = 1;
			} else if (returnValue == 1) {
				//does nothing
			}
		if (closeFrame == 1) {
			this.dispose();
		}
		}
	
	}

   			
   		
   
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new starter().setVisible(true);
           }
       });
   }
   
   public String getCell() {
	   return this.cells;
   }
   public String getButt() {
	   return this.butt;
   }
   public File getFile() {
	   return this.file;
   }
   
   private BufferedWriter writer;
   private String cells;
   private String butt;
   private String fileName;
   private File file;
   // Variables declaration - do not modify                     
   private javax.swing.JPanel bg;
   private javax.swing.JTextField butT;
   private javax.swing.JTextField cellT;
   private javax.swing.JButton exitB;
   private javax.swing.JPanel holder;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JTextField nameT;
   private javax.swing.JButton saveB;
   // End of variables declaration                   

}
